spring.application.name=aroma-origem

# Importa o arquivo de segredos de forma opcional e segura para o Git
spring.config.import=optional:file:src/main/resources/secrets.properties

# Configuração da Conexão com o PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/aroma_origem
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect